name: sijantan2
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_screenutil: ^5.7.0
  json_annotation: ^4.6.0
  dio: ^5.0.2
  logger: ^1.3.0
  geojson: ^1.0.0
  flutter_map: ^3.1.0
  flutter_map_geojson: ^1.0.1
  smooth_page_indicator: ^1.0.1
  flutter_inappwebview: ^5.7.2+3
  collection: ^1.17.0
  latlng: ^0.2.0
  latlong2: ^0.8.1
  font_awesome_flutter: ^10.4.0
  flutter_map_tappable_polyline:
    git: https://github.com/jtthrillson/flutter_map_tappable_polyline.git
  flutter_map_marker_cluster: ^1.1.0
  cached_network_image: ^3.2.3
  dropdown_search: ^5.0.6
  photo_view: ^0.14.0
  pie_chart: ^5.3.2
  graphic: ^1.0.1
  flutter_windowmanager: ^0.2.0
  skeletons: ^0.0.3
  url_launcher: ^6.1.10
  image_picker: ^0.8.7+1
  flutter_pagination: ^0.0.8

dev_dependencies: 
  flutter_lints: ^2.0.0
  build_runner: any
  flutter_launcher_icons: ^0.11.0
  hive_generator: any 
  json_serializable: any
  retrofit_generator: any
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
  #- assets/fonts/
  #- assets/svg/
  - assets/image/
  - assets/json/
  #- assets/icon/

flutter_icons:
  android: "launcher_icon"
  ios: true 
  image_path: "assets/image/launcher.jpg"
  adaptive_icon_background: "#2596be"
  min_sdk_android: 19

flutter_app_name:
  name: "SIJANTAN"

